- name: remove infra
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    provider: vmware
    environment: dev
  vars_files:
    - node-config/{{ environment }}/nodes-{{ provider }}.yml

  roles:
    - role: ansible-role-{{ provider }}
      role_action: deprovision
      delegate_to: localhost
      run_once: yes